name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or the Node.js version your project uses
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /RollForge # Replace with your repository name if different
          NEXT_PUBLIC_ASSET_PREFIX: /RollForge/ # Replace with your repository name if different

      - name: Export static site
        run: next export # Assuming you have an "export" script in your package.json for static export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Or the output directory of your build/export
          publish_branch: gh-pages
          enable_jekyll: false